version: '3.8'
services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: shareit-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      SHAREIT_SERVER_URL: http://server:9090

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SHAREIT_DB_URL=jdbc:postgresql://db:5432/shareit
      - SHAREIT_DB_USERNAME=postgres
      - SHAREIT_DB_PASSWORD=pswpsw

  db:
    image: postgres:14.3-alpine
    container_name: shareit-db
    restart: always
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pswpsw
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./postgres_db:/var/lib/postgresql/data